import {
  Injectable,
  NotFoundException,
  BadRequestException,
  ForbiddenException,
} from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository, DataSource, Between, MoreThanOrEqual, LessThanOrEqual } from 'typeorm';
import { PurchaseOrder } from './entities/purchase-order.entity';
import { PurchaseOrderLineItem } from './entities/purchase-order-line-item.entity';
import { PurchaseRequest } from '../procurement/entities/purchase-request.entity';
import { PoStatus } from '../common/enums/po-status.enum';
import { AuditAction } from '../common/enums/audit-action.enum';
import { NotificationType } from '../common/enums/notification-type.enum';
import { Role } from '../common/enums/role.enum';
import { AuditService } from '../audit/audit.service';
import { NotificationService } from '../notifications/notification.service';
import { BudgetService } from '../budget/budget.service';
import { QueryPosDto } from './dto/query-pos.dto';
import { UpdatePoDto } from './dto/update-po.dto';
import { FindOptionsWhere } from 'typeorm';

export interface BudgetOverrideContext {
  authorized: true;
  reason: string;
  role: string;
}

const CANCELLABLE_STATUSES = [PoStatus.DRAFT, PoStatus.ISSUED, PoStatus.PARTIALLY_RECEIVED];

@Injectable()
export class PurchaseOrdersService {
  constructor(
    @InjectRepository(PurchaseOrder)
    private readonly poRepo: Repository<PurchaseOrder>,
    @InjectRepository(PurchaseOrderLineItem)
    private readonly poLineItemRepo: Repository<PurchaseOrderLineItem>,
    private readonly dataSource: DataSource,
    private readonly auditService: AuditService,
    private readonly notificationService: NotificationService,
    private readonly budgetService: BudgetService,
  ) {}

  private async generatePoNumber(): Promise<string> {
    const result = await this.dataSource.query(`SELECT nextval('po_number_seq') as seq`);
    const seq = parseInt(result[0].seq, 10);
    const year = new Date().getFullYear();
    return `PO-${year}-${String(seq).padStart(5, '0')}`;
  }

  async generateFromRequest(request: PurchaseRequest, createdBy: string): Promise<PurchaseOrder> {
    const poNumber = await this.generatePoNumber();

    const lineItems = request.lineItems.map((li) => {
      const item = new PurchaseOrderLineItem();
      item.description = li.itemDescription;
      item.quantity = Number(li.quantity);
      item.unitPrice = Number(li.unitPrice);
      item.totalPrice = Number(li.totalPrice);
      item.quantityReceived = 0;
      item.catalogItemId = li.catalogItemId ?? null;
      return item;
    });

    const po = this.poRepo.create({
      poNumber,
      requestId: request.id,
      supplierId: request.supplierId,
      lineItems,
      totalAmount: Number(request.totalAmount),
      status: PoStatus.DRAFT,
      createdBy,
    });

    const saved = await this.poRepo.save(po);

    await this.auditService.log(createdBy, AuditAction.PO_CREATED, 'PurchaseOrder', saved.id, {
      poNumber: saved.poNumber,
      requestId: request.id,
      totalAmount: saved.totalAmount,
      autoGenerated: true,
    });

    await this.notificationService.emit(
      createdBy,
      NotificationType.PO_ISSUED,
      'Purchase Order Created',
      `A draft purchase order ${saved.poNumber} has been generated from request ${request.requestNumber}.`,
      { type: 'PurchaseOrder', id: saved.id },
    );

    return this.findById(saved.id);
  }

  async findAll(query: QueryPosDto) {
    const page = parseInt(query.page || '1', 10);
    const limit = Math.min(parseInt(query.limit || '20', 10), 100);
    const skip = (page - 1) * limit;

    const where: FindOptionsWhere<PurchaseOrder> = {};
    if (query.status) where.status = query.status;
    if (query.supplierId) where.supplierId = query.supplierId;
    if (query.dateFrom && query.dateTo) {
      where.createdAt = Between(new Date(query.dateFrom), new Date(query.dateTo)) as any;
    } else if (query.dateFrom) {
      where.createdAt = MoreThanOrEqual(new Date(query.dateFrom)) as any;
    } else if (query.dateTo) {
      where.createdAt = LessThanOrEqual(new Date(query.dateTo)) as any;
    }

    const sortBy = query.sortBy || 'createdAt';
    const sortOrder = (query.sortOrder?.toUpperCase() === 'ASC' ? 'ASC' : 'DESC') as 'ASC' | 'DESC';
    const allowedSorts = ['poNumber', 'totalAmount', 'status', 'createdAt', 'issuedAt'];
    const orderField = allowedSorts.includes(sortBy) ? sortBy : 'createdAt';

    const [data, total] = await this.poRepo.findAndCount({
      where,
      relations: ['supplier', 'request', 'lineItems'],
      order: { [orderField]: sortOrder },
      skip,
      take: limit,
    });

    return {
      data,
      meta: { page, limit, total, totalPages: Math.ceil(total / limit) },
    };
  }

  async findById(id: string): Promise<PurchaseOrder> {
    const po = await this.poRepo.findOne({
      where: { id },
      relations: ['supplier', 'request', 'lineItems', 'creator'],
    });
    if (!po) throw new NotFoundException('Purchase order not found');
    return po;
  }

  async update(id: string, dto: UpdatePoDto, userId?: string): Promise<PurchaseOrder> {
    const po = await this.findById(id);
    if (po.status === PoStatus.CANCELLED || po.status === PoStatus.CLOSED) {
      throw new BadRequestException('Cannot update a cancelled or closed PO');
    }
    const deliveryDateChanged =
      dto.expectedDeliveryDate !== undefined &&
      String(dto.expectedDeliveryDate) !== String(po.expectedDeliveryDate);
    if (dto.expectedDeliveryDate !== undefined) po.expectedDeliveryDate = dto.expectedDeliveryDate;
    if (dto.notes !== undefined) po.notes = dto.notes;
    await this.poRepo.save(po);

    if (deliveryDateChanged && po.createdBy) {
      await this.notificationService.emit(
        po.createdBy,
        NotificationType.SCHEDULE_CHANGE,
        'Delivery Date Updated',
        `The expected delivery date for purchase order ${po.poNumber} has been updated.`,
        { type: 'PurchaseOrder', id: po.id },
      );
    }

    return this.findById(id);
  }

  async issue(
    id: string,
    userId: string,
    override?: BudgetOverrideContext,
  ): Promise<PurchaseOrder> {
    await this.dataSource.transaction(async (manager) => {
      const po = await manager.findOne(PurchaseOrder, { where: { id } });
      if (!po) throw new NotFoundException('Purchase order not found');
      if (po.status !== PoStatus.DRAFT) {
        throw new BadRequestException('Only DRAFT purchase orders can be issued');
      }

      // ── Budget cap enforcement ───────────────────────────────────────────────
      if (po.supplierId) {
        const budget = await this.budgetService.checkAndEnforce(
          manager,
          po.supplierId,
          Number(po.totalAmount),
        );

        if (!budget.allowed) {
          if (!override?.authorized) {
            throw new BadRequestException(
              `Budget cap exceeded for this supplier. ` +
                `Cap: $${budget.cap?.toFixed(2)}, ` +
                `Committed: $${budget.committed.toFixed(2)}, ` +
                `Available: $${budget.available?.toFixed(2)}, ` +
                `Required: $${Number(po.totalAmount).toFixed(2)}. ` +
                `An ADMINISTRATOR override with a reason is required to proceed.`,
            );
          }

          if (override.role !== Role.ADMINISTRATOR) {
            throw new ForbiddenException(
              'Budget cap override requires ADMINISTRATOR role',
            );
          }

          await this.budgetService.recordOverride(
            manager,
            po.id,
            po.supplierId,
            userId,
            Number(po.totalAmount),
            budget.available ?? 0,
            override.reason,
          );
        }
      }
      // ─────────────────────────────────────────────────────────────────────────

      po.status = PoStatus.ISSUED;
      po.issuedAt = new Date();
      await manager.save(po);

      await this.auditService.log(userId, AuditAction.PO_ISSUED, 'PurchaseOrder', po.id, {
        poNumber: po.poNumber,
        issuedAt: po.issuedAt,
      });

      if (po.createdBy) {
        await this.notificationService.emit(
          po.createdBy,
          NotificationType.PO_ISSUED,
          'Purchase Order Issued',
          `Purchase order ${po.poNumber} has been issued to the supplier.`,
          { type: 'PurchaseOrder', id: po.id },
        );
      }
    });
    return this.findById(id);
  }

  async cancel(id: string, userId: string): Promise<PurchaseOrder> {
    await this.dataSource.transaction(async (manager) => {
      const po = await manager.findOne(PurchaseOrder, { where: { id } });
      if (!po) throw new NotFoundException('Purchase order not found');
      if (!CANCELLABLE_STATUSES.includes(po.status)) {
        throw new BadRequestException(
          `Cannot cancel a PO with status ${po.status}`,
        );
      }

      const previousStatus = po.status;
      po.status = PoStatus.CANCELLED;
      await manager.save(po);

      await this.auditService.log(userId, AuditAction.PO_CANCELLED, 'PurchaseOrder', po.id, {
        poNumber: po.poNumber,
        previousStatus,
      });

      if (po.createdBy) {
        await this.notificationService.emit(
          po.createdBy,
          NotificationType.CANCELLATION,
          'Purchase Order Cancelled',
          `Purchase order ${po.poNumber} has been cancelled.`,
          { type: 'PurchaseOrder', id: po.id },
        );
      }
    });
    return this.findById(id);
  }

  // Used by the receiving module (Prompt 7) to update status
  async updateStatusAfterReceiving(
    id: string,
    userId: string,
    status: PoStatus.PARTIALLY_RECEIVED | PoStatus.FULLY_RECEIVED,
  ): Promise<void> {
    await this.poRepo.update(id, { status });
    await this.auditService.log(userId, AuditAction.PO_STATUS_CHANGED, 'PurchaseOrder', id, {
      newStatus: status,
    });
  }

  // Supplier portal — only POs belonging to the supplier
  async findForSupplier(supplierId: string, query: QueryPosDto) {
    const page = parseInt(query.page || '1', 10);
    const limit = Math.min(parseInt(query.limit || '20', 10), 50);
    const skip = (page - 1) * limit;

    const visibleStatuses = [
      PoStatus.ISSUED,
      PoStatus.PARTIALLY_RECEIVED,
      PoStatus.FULLY_RECEIVED,
      PoStatus.CLOSED,
    ];

    const qb = this.poRepo
      .createQueryBuilder('po')
      .leftJoinAndSelect('po.lineItems', 'lineItems')
      .leftJoinAndSelect('po.supplier', 'supplier')
      .where('po.supplierId = :supplierId', { supplierId })
      .andWhere('po.status IN (:...statuses)', { statuses: visibleStatuses })
      .orderBy('po.createdAt', 'DESC')
      .skip(skip)
      .take(limit);

    if (query.status && visibleStatuses.includes(query.status as PoStatus)) {
      qb.andWhere('po.status = :status', { status: query.status });
    }

    const [data, total] = await qb.getManyAndCount();
    return { data, meta: { page, limit, total, totalPages: Math.ceil(total / limit) } };
  }

  async findByIdForSupplier(id: string, supplierId: string): Promise<PurchaseOrder> {
    const visibleStatuses = [
      PoStatus.ISSUED,
      PoStatus.PARTIALLY_RECEIVED,
      PoStatus.FULLY_RECEIVED,
      PoStatus.CLOSED,
    ];

    const po = await this.poRepo.findOne({
      where: { id, supplierId },
      relations: ['supplier', 'lineItems'],
    });

    if (!po || !visibleStatuses.includes(po.status)) {
      throw new NotFoundException('Purchase order not found');
    }
    return po;
  }
}
