export enum Role {
  PROCUREMENT_MANAGER = 'PROCUREMENT_MANAGER',
  WAREHOUSE_CLERK = 'WAREHOUSE_CLERK',
  PLANT_CARE_SPECIALIST = 'PLANT_CARE_SPECIALIST',
  ADMINISTRATOR = 'ADMINISTRATOR',
  SUPPLIER = 'SUPPLIER',
}
